id: P007055
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W20831
  title: ལྡེའུ་ཆོས་འབྱུང
  author: ''
  volumes:
    fb66cf003782430ba1e8e696c9e625c6:
      image_group_id: I4239
      title: ''
      volume_number: 1
      total_pages: 176
      base_file: v001.txt
