id: opecha:P007055
initial_creation_type: ocr
source_metadata:
  id: bdr:W20831
  title: ལྡེའུ་ཆོས་འབྱུང
  volume:
    09f095e8d9854755b30d1c57a065e885:
      image_group_id: I4239
      title: ''
      volume_number: 1
      total_pages: 176
  author: ''
ebook_metadata:
  title: ལྡེའུ་ཆོས་འབྱུང
  author: ''
  sku: P007055
  cover: cover.jpg
  layers:
  - pagination
