id: P007055
initial_creation_type: ocr
source_metadata:
  id: bdr:W20831
  title: ལྡེའུ་ཆོས་འབྱུང
  author: ''
  volumes:
    fb66cf003782430ba1e8e696c9e625c6:
      image_group_id: I4239
      title: ''
      volume_number: 1
      total_pages: 176
ebook_metadata:
  title: ལྡེའུ་ཆོས་འབྱུང
  author: ''
  sku: P007055
  cover: cover.jpg
  layers:
  - pagination
